# Generated by Django 4.1.7 on 2023-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase_from',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('creditCard', 'Credit Card'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
